"""empty message

Revision ID: 9019b6afb004
Revises: 19f797258971
Create Date: 2022-06-02 22:44:30.437840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9019b6afb004'
down_revision = '19f797258971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'genres')
    # ### end Alembic commands ###
