"""empty message

Revision ID: a63e36c94b37
Revises: 9019b6afb004
Create Date: 2022-06-02 22:46:37.654163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63e36c94b37'
down_revision = '9019b6afb004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Artists', 'web')
    op.add_column('Venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Venues', 'web')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('web', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venues', 'website')
    op.drop_column('Venues', 'genres')
    op.add_column('Artists', sa.Column('web', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artists', 'website')
    # ### end Alembic commands ###
